apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ml-recc
            port:
              number: 6969