apiVersion: skaffold/v2alpha1 
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ml-recc
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**

portForward:
- resourceType: service
  resourceName: ml-recc
  port: 80
  address: 0.0.0.0
