apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
        containers:
            - image: postgres:12
              imagePullPolicy: "IfNotPresent"
              name: postgres
              envFrom:
                  - configMapRef:
                     name: postgres-config
              ports:
              - containerPort: 5432
                name: postgresdb
              volumeMounts:
              - name: postgres-persistent-storage
                mountPath: /var/lib/postgresql/data
        volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

            

